import { IssueCategory, IssueStatus } from '../types';

interface SeedIssue {
  title: string;
  description: string;
  category: IssueCategory;
  status: IssueStatus;
  photoUrl: string;
  lat: number;
  lng: number;
  createdBy: string;
  upvotes: number;
  upvoters: string[];
}

export const ISSUES_SEED: SeedIssue[] = [
  // --- EDUCATION (3) ---
  {
    title: 'Протекает крыша в школе №47',
    description: 'В нескольких классах третьего этажа протекает крыша после дождей. Учителя вынуждены переносить уроки. Потолок уже покрылся плесенью.',
    category: 'education',
    status: 'open',
    photoUrl: '',
    lat: 41.3123,
    lng: 69.2415,
    createdBy: 'seed_user_1',
    upvotes: 38,
    upvoters: [],
  },
  {
    title: 'Нет отопления в школе №12 (Чиланзар)',
    description: 'Батареи не работают с начала ноября. Дети сидят в куртках, температура в классах около 10°C.',
    category: 'education',
    status: 'problem',
    photoUrl: '',
    lat: 41.2964,
    lng: 69.2071,
    createdBy: 'seed_user_2',
    upvotes: 54,
    upvoters: [],
  },
  {
    title: 'Туалеты в школе №88 требуют ремонта',
    description: 'Унитазы сломаны в мужских туалетах на 1 и 2 этажах. Дети вынуждены ходить домой или в соседние заведения.',
    category: 'education',
    status: 'open',
    photoUrl: '',
    lat: 41.3301,
    lng: 69.2630,
    createdBy: 'seed_user_3',
    upvotes: 21,
    upvoters: [],
  },

  // --- HEALTHCARE (3) ---
  {
    title: 'Поликлиника №7: очереди по 4–5 часов',
    description: 'Электронная запись не работает уже 3 месяца. Люди занимают очередь с 5 утра. Пожилые пациенты не могут долго стоять.',
    category: 'healthcare',
    status: 'open',
    photoUrl: '',
    lat: 41.3058,
    lng: 69.2339,
    createdBy: 'seed_user_4',
    upvotes: 42,
    upvoters: [],
  },
  {
    title: 'Отсутствие скорой помощи в Юнусабадском районе',
    description: 'Скорая приезжает через 45–60 минут. Две машины сломаны, одна в ремонте. Нужны срочные меры.',
    category: 'healthcare',
    status: 'problem',
    photoUrl: '',
    lat: 41.3562,
    lng: 69.2891,
    createdBy: 'seed_user_5',
    upvotes: 67,
    upvoters: [],
  },
  {
    title: 'Нет педиатра в поликлинике №15 три месяца',
    description: 'Детский врач уволился в августе. Замену так и не нашли. Родителей отправляют в другой район.',
    category: 'healthcare',
    status: 'open',
    photoUrl: '',
    lat: 41.2877,
    lng: 69.1934,
    createdBy: 'seed_user_6',
    upvotes: 29,
    upvoters: [],
  },

  // --- TRANSPORT (3) ---
  {
    title: 'Яма на пересечении ул. Буюк Ипак Йули и Шахристан',
    description: 'Огромная яма диаметром около 1.5м и глубиной 30см. Уже несколько аварий. Дорожники знают, но ничего не делают.',
    category: 'transport',
    status: 'open',
    photoUrl: '',
    lat: 41.3211,
    lng: 69.2518,
    createdBy: 'seed_user_7',
    upvotes: 89,
    upvoters: [],
  },
  {
    title: 'Автобус №67 ходит раз в час вместо 20 минут',
    description: 'После ремонта расписание изменили, но не обновили на остановках. Люди ждут по часу на жаре.',
    category: 'transport',
    status: 'done',
    photoUrl: '',
    lat: 41.3099,
    lng: 69.2203,
    createdBy: 'seed_user_8',
    upvotes: 33,
    upvoters: [],
  },
  {
    title: 'Отсутствие светофора на опасном перекрёстке Сергели',
    description: 'Перекрёсток у ТЦ «Мегапланет» не оснащён светофором. За последний месяц 3 ДТП с пострадавшими.',
    category: 'transport',
    status: 'open',
    photoUrl: '',
    lat: 41.2701,
    lng: 69.2012,
    createdBy: 'seed_user_9',
    upvotes: 77,
    upvoters: [],
  },

  // --- ECOLOGY (3) ---
  {
    title: 'Стихийная свалка в Мирзо-Улугбекском районе',
    description: 'На пустыре у канала выросла огромная мусорная свалка. Запах распространяется на несколько кварталов. Дети играют рядом.',
    category: 'ecology',
    status: 'open',
    photoUrl: '',
    lat: 41.3401,
    lng: 69.3102,
    createdBy: 'seed_user_10',
    upvotes: 55,
    upvoters: [],
  },
  {
    title: 'Завод сбрасывает отходы в арык',
    description: 'По ночам из трубы завода в арык текут тёмные жидкости. Рыба в канале погибла. Вода имеет химический запах.',
    category: 'ecology',
    status: 'problem',
    photoUrl: '',
    lat: 41.2988,
    lng: 69.3344,
    createdBy: 'seed_user_11',
    upvotes: 103,
    upvoters: [],
  },
  {
    title: 'Вырубка деревьев во дворе на ул. Амир Темур',
    description: '14 взрослых тополей срублены без ведома жильцов. На их месте планируется парковка. Двор потеряет всю тень.',
    category: 'ecology',
    status: 'open',
    photoUrl: '',
    lat: 41.3155,
    lng: 69.2760,
    createdBy: 'seed_user_12',
    upvotes: 48,
    upvoters: [],
  },

  // --- SAFETY (3) ---
  {
    title: 'Сломанное уличное освещение на ул. Навои (3 км)',
    description: 'Три километра улицы без освещения. Вечером очень опасно: несколько случаев грабежей уже зафиксировано.',
    category: 'safety',
    status: 'open',
    photoUrl: '',
    lat: 41.3078,
    lng: 69.2581,
    createdBy: 'seed_user_13',
    upvotes: 61,
    upvoters: [],
  },
  {
    title: 'Открытый канализационный люк у рынка Чорсу',
    description: 'Крышка люка пропала неделю назад. Яма никак не огорожена, ночью невидима. Уже одна пострадавшая.',
    category: 'safety',
    status: 'done',
    photoUrl: '',
    lat: 41.3262,
    lng: 69.2320,
    createdBy: 'seed_user_14',
    upvotes: 44,
    upvoters: [],
  },
  {
    title: 'Заброшенное здание используется для сходок',
    description: 'Старый завод в Яккасарайском районе: разбитые окна, открытые входы. Местные жители боятся за детей.',
    category: 'safety',
    status: 'open',
    photoUrl: '',
    lat: 41.2912,
    lng: 69.2677,
    createdBy: 'seed_user_15',
    upvotes: 19,
    upvoters: [],
  },

  // --- URBAN (3) ---
  {
    title: 'Разбитая детская площадка в 5-м квартале Чиланзара',
    description: 'Горка сломана, качели без сидений, покрытие порвано. Дети получают травмы. Заявка в хокимият была подана 4 месяца назад.',
    category: 'urban',
    status: 'open',
    photoUrl: '',
    lat: 41.2945,
    lng: 69.2133,
    createdBy: 'seed_user_16',
    upvotes: 36,
    upvoters: [],
  },
  {
    title: 'Тротуар вдоль ул. Беруни полностью разрушен',
    description: 'Плитка выбита, ямы, грязь. Пешеходы вынуждены идти по проезжей части. Особенно опасно для мам с колясками.',
    category: 'urban',
    status: 'open',
    photoUrl: '',
    lat: 41.3188,
    lng: 69.2445,
    createdBy: 'seed_user_17',
    upvotes: 52,
    upvoters: [],
  },
  {
    title: 'Стихийная торговля загораживает вход в метро',
    description: 'У станции «Буюк Ипак Йули» продавцы занимают тротуар, люди вынуждены выходить на дорогу.',
    category: 'urban',
    status: 'done',
    photoUrl: '',
    lat: 41.3090,
    lng: 69.2502,
    createdBy: 'seed_user_18',
    upvotes: 27,
    upvoters: [],
  },

  // --- UTILITIES (3) ---
  {
    title: 'Газ отключён в 6 домах на ул. Катартол',
    description: 'Уже 10 дней без газа. Официального уведомления не было. Жильцы готовят еду на электроплитках, счета растут.',
    category: 'utilities',
    status: 'open',
    photoUrl: '',
    lat: 41.3350,
    lng: 69.2198,
    createdBy: 'seed_user_19',
    upvotes: 73,
    upvoters: [],
  },
  {
    title: 'Мусор не вывозят 2 недели в Юнусабаде',
    description: 'Контейнерные площадки переполнены, мусор разлетается по улицам. Коммунальщики не отвечают на звонки.',
    category: 'utilities',
    status: 'problem',
    photoUrl: '',
    lat: 41.3511,
    lng: 69.2813,
    createdBy: 'seed_user_20',
    upvotes: 58,
    upvoters: [],
  },
  {
    title: 'Лифт не работает 3 месяца в 9-этажном доме',
    description: 'Пожилые жильцы и мамы с колясками не могут нормально выходить. Управляющая компания игнорирует обращения.',
    category: 'utilities',
    status: 'open',
    photoUrl: '',
    lat: 41.3022,
    lng: 69.2660,
    createdBy: 'seed_user_21',
    upvotes: 41,
    upvoters: [],
  },

  // --- WATER (3) ---
  {
    title: 'Холодная вода подаётся только по ночам (Алмазар)',
    description: 'С июня вода есть только с 23:00 до 6:00. Днём давление ноль. Жители набирают в ёмкости. Уже 3 месяца.',
    category: 'water',
    status: 'open',
    photoUrl: '',
    lat: 41.3440,
    lng: 69.2551,
    createdBy: 'seed_user_22',
    upvotes: 96,
    upvoters: [],
  },
  {
    title: 'Прорыв трубы на ул. Паркентская, вода на дороге',
    description: 'Вода течёт по улице уже 5 дней. Образовалась огромная лужа, асфальт разрушается. Аварийная служба не реагирует.',
    category: 'water',
    status: 'done',
    photoUrl: '',
    lat: 41.3285,
    lng: 69.3011,
    createdBy: 'seed_user_23',
    upvotes: 83,
    upvoters: [],
  },
  {
    title: 'Грязная вода из крана (мутная, с запахом)',
    description: 'Вода жёлтого цвета с запахом тины. Дети жалуются на боли в животе. Лабораторный анализ не сделан.',
    category: 'water',
    status: 'open',
    photoUrl: '',
    lat: 41.2998,
    lng: 69.2389,
    createdBy: 'seed_user_24',
    upvotes: 112,
    upvoters: [],
  },

  // --- ENERGY (3) ---
  {
    title: 'Отключения электричества по 8 часов в Сергели',
    description: 'Ежедневные веерные отключения с 9:00 до 17:00. Холодильники не работают, еда портится. Официальных объяснений нет.',
    category: 'energy',
    status: 'open',
    photoUrl: '',
    lat: 41.2655,
    lng: 69.2088,
    createdBy: 'seed_user_25',
    upvotes: 118,
    upvoters: [],
  },
  {
    title: 'Оборванные провода на столбе у школы',
    description: 'После шторма оборвались провода. Концы лежат на тротуаре, огорожены лишь наспех поставленным ведром.',
    category: 'energy',
    status: 'problem',
    photoUrl: '',
    lat: 41.3177,
    lng: 69.2722,
    createdBy: 'seed_user_26',
    upvotes: 85,
    upvoters: [],
  },
  {
    title: 'Уличные фонари работают днём, а ночью — нет',
    description: 'Датчик освещения неисправен: фонари горят с 6 до 18 часов. Ночью улица тёмная. Жалобы в «Тошшахартрансхизмат» без ответа.',
    category: 'energy',
    status: 'open',
    photoUrl: '',
    lat: 41.3067,
    lng: 69.2364,
    createdBy: 'seed_user_27',
    upvotes: 31,
    upvoters: [],
  },
];
