import { School, Report } from '../types';

export const SCHOOLS_SEED: School[] = [
  {
    id: 'school-47',
    name: 'Школа №47',
    district: 'Мирзо-Улугбек',
    lat: 41.3123,
    lng: 69.2887,
    coverPhotoUrl: 'https://picsum.photos/seed/school47/400/250',
    promises: [
      { id: 'p47-1', labelKey: 'promise.fixToilets', category: 'sanitation' },
      { id: 'p47-2', labelKey: 'promise.soapDispensers', category: 'sanitation' },
      { id: 'p47-3', labelKey: 'promise.newDesks', category: 'education' },
    ],
  },
  {
    id: 'school-15',
    name: 'Школа №15',
    district: 'Юнусабад',
    lat: 41.3456,
    lng: 69.2765,
    coverPhotoUrl: 'https://picsum.photos/seed/school15/400/250',
    promises: [
      { id: 'p15-1', labelKey: 'promise.fixToilets', category: 'sanitation' },
      { id: 'p15-2', labelKey: 'promise.cleanWater', category: 'sanitation' },
      { id: 'p15-3', labelKey: 'promise.computerLab', category: 'education' },
    ],
  },
  {
    id: 'school-208',
    name: 'Школа №208',
    district: 'Чиланзар',
    lat: 41.2987,
    lng: 69.2234,
    coverPhotoUrl: 'https://picsum.photos/seed/school208/400/250',
    promises: [
      { id: 'p208-1', labelKey: 'promise.soapDispensers', category: 'sanitation' },
      { id: 'p208-2', labelKey: 'promise.fixWindows', category: 'safety' },
      { id: 'p208-3', labelKey: 'promise.libraryBooks', category: 'education' },
    ],
  },
  {
    id: 'school-91',
    name: 'Школа №91',
    district: 'Шайхантаур',
    lat: 41.3201,
    lng: 69.2456,
    coverPhotoUrl: 'https://picsum.photos/seed/school91/400/250',
    promises: [
      { id: 'p91-1', labelKey: 'promise.fixToilets', category: 'sanitation' },
      { id: 'p91-2', labelKey: 'promise.repairFence', category: 'safety' },
      { id: 'p91-3', labelKey: 'promise.whiteboards', category: 'education' },
    ],
  },
  {
    id: 'school-33',
    name: 'Школа №33',
    district: 'Яккасарай',
    lat: 41.2876,
    lng: 69.2567,
    coverPhotoUrl: 'https://picsum.photos/seed/school33/400/250',
    promises: [
      { id: 'p33-1', labelKey: 'promise.cleanWater', category: 'sanitation' },
      { id: 'p33-2', labelKey: 'promise.fireExtinguisher', category: 'safety' },
      { id: 'p33-3', labelKey: 'promise.newDesks', category: 'education' },
    ],
  },
  {
    id: 'school-112',
    name: 'Школа №112',
    district: 'Учтепа',
    lat: 41.2765,
    lng: 69.2123,
    coverPhotoUrl: 'https://picsum.photos/seed/school112/400/250',
    promises: [
      { id: 'p112-1', labelKey: 'promise.soapDispensers', category: 'sanitation' },
      { id: 'p112-2', labelKey: 'promise.fixWindows', category: 'safety' },
      { id: 'p112-3', labelKey: 'promise.computerLab', category: 'education' },
    ],
  },
  {
    id: 'school-76',
    name: 'Школа №76',
    district: 'Бектемир',
    lat: 41.2654,
    lng: 69.3456,
    coverPhotoUrl: 'https://picsum.photos/seed/school76/400/250',
    promises: [
      { id: 'p76-1', labelKey: 'promise.fixToilets', category: 'sanitation' },
      { id: 'p76-2', labelKey: 'promise.repairFence', category: 'safety' },
      { id: 'p76-3', labelKey: 'promise.libraryBooks', category: 'education' },
    ],
  },
  {
    id: 'school-55',
    name: 'Школа №55',
    district: 'Сергели',
    lat: 41.2543,
    lng: 69.2789,
    coverPhotoUrl: 'https://picsum.photos/seed/school55/400/250',
    promises: [
      { id: 'p55-1', labelKey: 'promise.cleanWater', category: 'sanitation' },
      { id: 'p55-2', labelKey: 'promise.fireExtinguisher', category: 'safety' },
      { id: 'p55-3', labelKey: 'promise.whiteboards', category: 'education' },
    ],
  },
  {
    id: 'school-189',
    name: 'Школа №189',
    district: 'Алмазар',
    lat: 41.3345,
    lng: 69.2654,
    coverPhotoUrl: 'https://picsum.photos/seed/school189/400/250',
    promises: [
      { id: 'p189-1', labelKey: 'promise.soapDispensers', category: 'sanitation' },
      { id: 'p189-2', labelKey: 'promise.fixWindows', category: 'safety' },
      { id: 'p189-3', labelKey: 'promise.newDesks', category: 'education' },
    ],
  },
  {
    id: 'school-23',
    name: 'Школа №23',
    district: 'Яшнабад',
    lat: 41.2432,
    lng: 69.3012,
    coverPhotoUrl: 'https://picsum.photos/seed/school23/400/250',
    promises: [
      { id: 'p23-1', labelKey: 'promise.fixToilets', category: 'sanitation' },
      { id: 'p23-2', labelKey: 'promise.repairFence', category: 'safety' },
      { id: 'p23-3', labelKey: 'promise.computerLab', category: 'education' },
    ],
  },
];

const PLACEHOLDER_PHOTO = 'https://picsum.photos/seed/report/400/300';

export const DEMO_REPORTS: Omit<Report, 'id'>[] = [
  { schoolId: 'school-47', promiseId: 'p47-1', status: 'done', photoUrl: PLACEHOLDER_PHOTO, comment: 'Туалеты отремонтированы!', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-47', promiseId: 'p47-2', status: 'problem', photoUrl: PLACEHOLDER_PHOTO, comment: 'Диспенсер пуст', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-47', promiseId: 'p47-3', status: 'done', photoUrl: PLACEHOLDER_PHOTO, comment: 'Новые парты установлены', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-15', promiseId: 'p15-1', status: 'done', photoUrl: PLACEHOLDER_PHOTO, comment: 'Всё хорошо', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-15', promiseId: 'p15-2', status: 'done', photoUrl: PLACEHOLDER_PHOTO, comment: 'Вода чистая', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-208', promiseId: 'p208-1', status: 'problem', photoUrl: PLACEHOLDER_PHOTO, comment: 'Диспенсеры не работают', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-208', promiseId: 'p208-2', status: 'problem', photoUrl: PLACEHOLDER_PHOTO, comment: 'Окна всё ещё разбиты', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-91', promiseId: 'p91-1', status: 'done', photoUrl: PLACEHOLDER_PHOTO, comment: 'Отремонтировано', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-91', promiseId: 'p91-3', status: 'done', photoUrl: PLACEHOLDER_PHOTO, comment: 'Доска установлена', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-33', promiseId: 'p33-1', status: 'done', photoUrl: PLACEHOLDER_PHOTO, comment: '', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-33', promiseId: 'p33-3', status: 'done', photoUrl: PLACEHOLDER_PHOTO, comment: 'Парты новые', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-112', promiseId: 'p112-1', status: 'problem', photoUrl: PLACEHOLDER_PHOTO, comment: 'Диспенсеры отсутствуют', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-76', promiseId: 'p76-1', status: 'done', photoUrl: PLACEHOLDER_PHOTO, comment: 'Всё чисто', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-76', promiseId: 'p76-2', status: 'done', photoUrl: PLACEHOLDER_PHOTO, comment: 'Забор починен', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-55', promiseId: 'p55-1', status: 'done', photoUrl: PLACEHOLDER_PHOTO, comment: '', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-189', promiseId: 'p189-2', status: 'problem', photoUrl: PLACEHOLDER_PHOTO, comment: 'Окна разбиты снова', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-23', promiseId: 'p23-1', status: 'done', photoUrl: PLACEHOLDER_PHOTO, comment: 'Хорошее состояние', timestamp: null, userId: 'demo-user' },
  { schoolId: 'school-23', promiseId: 'p23-3', status: 'done', photoUrl: PLACEHOLDER_PHOTO, comment: 'Компьютеры работают', timestamp: null, userId: 'demo-user' },
];
